# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OsmPoiDownloader
                                 A QGIS plugin
 Download Points of Interest from OpenStreetMap
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-30
        copyright            : (C) 2025 by Isidora Pavlovic
        email                : isidorapavlovic0@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OsmPoiDownloader class from file OsmPoiDownloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .osm_poi_downloader import OsmPoiDownloader
    return OsmPoiDownloader(iface)
